### PR TITLE
Fix typescript exports for ao-loader

### PR DESCRIPTION
**Pull request by jim-toth**

### CODE REVIEW

**Comment by TillaTheHun0** [comment]
Thanks for taking a look @jim-toth.

Maybe I am missing something, but I don't see how this fixes the issue. Building `aoconnect` uses `tsc` to build and emit the type declarations, as `*.d.ts` files, into `/dist`; there are no `.cts` files generated into the `dist` folder. My understanding is that, if anything, this would break the current types.

What #593 is concerned with is the ability to import the types directly, in a TS project.

**Comment by jim-toth** [comment]
> Thanks for taking a look @jim-toth.
> 
> Maybe I am missing something, but I don't see how the issue is addressed with these changes. Building `aoconnect` uses `tsc` to build and emit the type declarations, as `*.d.ts` files, into `/dist`; there are no `.cts` files generated into the `dist` folder. My understanding is that, if anything, this would break the current types.
> 
> What #593 is concerned with is the ability to import the types directly, in a TS project.

Well, I wasn't making a comment on the setup or what the files should be - just making a note of what worked for me.  That said, the types generated from the JSDoc comments in the source are out of date, so even getting the types imported correctly doesn't help much when they don't match the implementation.  I could open a PR or modify my PR to fix the JSDoc comments and thus generated types if you could provide the current interfaces - as i'm not as familiar with the implemented code.

Anyway, the `.cts` solution was because if you look at the package from npm, it has only two files one being a `*.d.cts*` which is why typescript can't find the files when it was told to look for `*.d.ts`.

See here for latest npm package with the `index.d.cts` file: https://www.npmjs.com/package/@permaweb/ao-loader?activeTab=code

See here for `package.json` explicitly looking for `index.d.ts`: https://github.com/permaweb/ao/blob/main/loader/package.json#L12

**Comment by TillaTheHun0** [comment]
Got it, okay I see. These changes are to do with `ao-loader` and not `aoconnect`. Yes, it does look like the `package.json` file references the wrong file for types, and to your point, those types are most likely out of date anyway (`ao-loader` is under a lot of flux!).

We will try to get those types updated on `ao-loader`, will create an issue for that. Thank you for pointing it out!

**Comment by jim-toth** [comment]
> Got it, okay I see. These changes are to do with `ao-loader` and not `aoconnect`.

Yep, and when using `@permaweb/ao-loader` the npm package points to this repository...which looks like a monorepo...

Is there another repository dedicated to `ao-loader` ?  Then the package.json should be updated to reflect this, so others don't wind up in this repo?

**Comment by jim-toth** [comment]
> @jim-toth yes it's a monorepo. `ao-loader` is [here](https://github.com/permaweb/ao/tree/main/loader)

Gotcha, sorry for the confusion!  We got there in the end 🤝

**Comment by TillaTheHun0** [comment]
Types for `aoloader` were updated in #954. @jim-toth can this be closed?

**Comment by TillaTheHun0** [comment]
Closing this for now, as I am dong some housekeeping. If I am misunderstanding, please let me and I can reopen. Thanks for bringing the types to our attention.

**Pull request closed without merging**
